# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  nome: Gerar Dados

em:
  horário:  # executar a cada 12 horas
    - cron:  "* */12 * * *" 
  workflow_dispatch:

empregos:
  construir:
    nome: Empregos para atualizar dados
    runs-on: ubuntu-latest
    passos:
      # Animação cobra
      - usos: Platane/snk@master
        id: snake-gif
        com:
          github_user_name: elizeu-lima
          svg_out_path: dist/github-contribution-grid-snake.svg

      - usa: crazy-max/ghaction-github-pages@v2.1.3
        com:
          target_branch: saída
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{{ segredos. GITHUB_TOKEN }}
